### ISSUE TITLE
[Crash] Crashes game when using version 1.0.5

### ISSUE THREAD

**Issue by AbandonedGaming** [SuperMartijn642/SuperMartijn642sConfigLib#1]
**Version Info**
- Minecraft, 1.16.4
- Config Lib, 1.0.5

**Steps to Reproduce**
Just launching the game.
(Combined with a few other mods.)

**Crash report (~/logs/latest.log)**
[See Attached File]
[latest.log](https://github.com/SuperMartijn642/SuperMartijn642sConfigLib/files/6481274/latest.log)

**Comment by SuperMartijn642** [comment]
That doesn't seem like it has to do with Config lib.
It crashes because of some incorrect mixin, however Config Lib doesn't have any mixins.

Does the issue appear with just Config Lib (and my mods that depend on Config Lib)?

**Comment by AbandonedGaming** [comment]
> 
> 
> That doesn't seem like it has to do with Config lib.
> It crashes because of some incorrect mixin, however Config Lib doesn't have any mixins.
> 
> Does the issue appear with just Config Lib (and my mods that depend on Config Lib)?

I found that when I removed another mod (the Immersive Portals mod) it's working just fine.  Sorry for taking up your time, it turned out to be the one mod that I didn't check.

**Comment by SuperMartijn642** [comment]
No worries, glad you found the issue now.
