### ISSUE TITLE
Crash With Dummy Mod

### ISSUE THREAD

**Issue by ItzRayker** [SuperMartijn642/SuperMartijn642sConfigLib#10]
**Version Info**
- Minecraft, 1.19
- Config Lib, 1.1.6b

**Steps to Reproduce**
...

**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/SuperMartijn642/SuperMartijn642sConfigLib/files/9234489/latest.log)

**Comment by SuperMartijn642** [comment]
I have no clue what this crash report has to do with my config library 🤔
