### ISSUE TITLE
[Crash] ClassNotFoundException with 1.1.6 and 1.18.2

### ISSUE THREAD

**Issue by Lxazl5770** [SuperMartijn642/SuperMartijn642sConfigLib#11]
Game crashed during started.
`Caused by 0: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.supermartijn642.configlib.ConfigLibClient`

Version: Mod version 1.1.6 with 1.18.2-Forge_40.1.52 (with Optifine H7)

Crash wouldn't happen in the same mod version with 1.16.5.
[crash-2022-09-03_13.43.35-fml.txt](https://github.com/SuperMartijn642/SuperMartijn642sConfigLib/files/9481877/crash-2022-09-03_13.43.35-fml.txt)

**Comment by SuperMartijn642** [comment]
Seems to be working fine with just my config library, so it is likely caused by some other mod.
You are using quite a lot of mods. Could you narrow down the mods needed to produce the issue?

**Comment by Lxazl5770** [comment]
My mistake, I just forgot to delete the old one of this mod, sorry!😂
