### ISSUE TITLE
[Crash] Game Crashes when Loading into a world.

### ISSUE THREAD

**Issue by MrSeven3** [SuperMartijn642/SuperMartijn642sConfigLib#12]
**Version Info**
- Minecraft, 1.19.2
- Config Lib, 1.1.6a

**Steps to Reproduce**
Open game and load into preexisting world with only a few mods loaded.

**Crash report (~/[latest.log]**
[latest.log](https://github.com/SuperMartijn642/SuperMartijn642sConfigLib/files/10892820/latest.log)

**Comment by SuperMartijn642** [comment]
The game loads fine with just my config library. Could you narrow down the mods needed to reproduce the issue?

**Comment by MrSeven3** [comment]
I'm running Chunk Loaders, Create, Create: Steam 'n Rails, Essential-Forge, Flywheel, Just Enough Items, Simple Voice Chat, Sound Physics Remastered, SuperMartjin642's Config Library, SuperMartjin642's Core Lib and World Edit

**Comment by SuperMartijn642** [comment]
Actually, now that I look at it, you're using an outdated version of my config library.
Please update to version 1.1.6b, it accounts for changes made in Forge 41.0.94.

**Comment by MrSeven3** [comment]
But 1.1.6b is built for 1.19.3, will it work on 1.19.2? If not, how can I play? Some of my mods don't have 1.19.3 options.

**Comment by MrSeven3** [comment]
Oh, it appears that did fix my problem, you should list that version as 1.19.2 compatible though.

**Comment by SuperMartijn642** [comment]
Yes it will work for 1.19.1, 1.19.2, and 1.19.3. Look at the game versions column on CurseForge.

**Comment by SuperMartijn642** [comment]
It is marked for 1.19.2.

**Comment by MrSeven3** [comment]
Oh ok, thanks!

**Comment by MrSeven3** [comment]
Didn't see this
![image](https://user-images.githubusercontent.com/127050193/223228362-cac581fc-ecc0-43ae-a41b-4cd865998823.png)

**Comment by SuperMartijn642** [comment]
Ah you're looking at the new website. On the old website it looks a bit more clear with a '+4':
![image](https://user-images.githubusercontent.com/12382965/223229868-bbe5fc20-44be-4dac-81f8-6c22c97a869c.png)
Hopefully they add that the new website as well soon.
