### ISSUE TITLE
[Bug] Configlib has failed to load correctly (1.19)

### ISSUE THREAD

**Issue by KarmaKayne** [SuperMartijn642/SuperMartijn642sConfigLib#14]
Download 1.1.5 for minecraft 1.19
- Minecraft
- Config Lib

It shows in error loading mods 'SuperMartijn642's Config Library has failed to load correctly' then underneath (in light gray) it says 'java.lang.reflect.InvocationTargetException: null' 

Is there a way to fix this?

**Comment by SuperMartijn642** [comment]
Update to a newer version.
Also, I have no clue what you mean, please provide the log next time.
