### ISSUE TITLE
[Crash] The latest update crashes my modpack

### ISSUE THREAD

**Issue by ekiplier** [SuperMartijn642/SuperMartijn642sConfigLib#15]
**Version Info**
- Minecraft, 1.16.5
- Config Lib, 1.1.7
(latest FML version for 1.16.5)

**Steps to Reproduce**
Install Config Lib;
Run my modpack;
See crash

**Crash report (~/logs/latest.log)**
[crash-2023-07-07_03.55.16-fml.txt](https://github.com/SuperMartijn642/SuperMartijn642sConfigLib/files/11974185/crash-2023-07-07_03.55.16-fml.txt)

[latest.log](https://github.com/SuperMartijn642/SuperMartijn642sConfigLib/files/11974189/latest.log)

**Comment by SuperMartijn642** [comment]
Fixed now, thank you for reporting the issue!
Also, 'Run my modpack;' is not a very useful reproduction step.

**Comment by ekiplier** [comment]
Glad to help! :) 
Sorry, I hadn't tested without all the mods, so I didn't know if it was a compatibility thing lol
