### ISSUE TITLE
New 1.20.1 version is not running on 1.20.1

### ISSUE THREAD

**Issue by icynstant** [SuperMartijn642/SuperMartijn642sConfigLib#16]
Minecraft 1.20.1
Config Lib supermartijn642configlib-1.1.7-fabric-mc1.19

supermartijn642configlib-1.1.6-fabric-mc1.20 work fine but supermartijn642configlib-1.1.7-fabric-mc1.19 is not and 1.1.7 version with "mc1.19" was given to me when i chose 1.20.1 on Modrinth when i saw an update in my minecraft
![Screenshot_1](https://github.com/SuperMartijn642/SuperMartijn642sConfigLib/assets/127024748/bb1ac7c6-5abb-4f04-89a2-2b941689756c)

so i think you just put wrong version on Modrinth and please delete update notification in MC if it's actually not a new version

**Comment by SuperMartijn642** [comment]
Fixed now
