### ISSUE TITLE
[Crash] NPE trying to access ModList.getModContainerByID too soon in ConfigLib.getModVersion

### ISSUE THREAD

**Issue by NighthowlerStudios** [SuperMartijn642/SuperMartijn642sConfigLib#17]
**Version Info**
- Minecraft, 1.16.5
- Config Lib, 1.1.7

**Steps to Reproduce**
1. Install latest into Kaleidio's Battle Pack 5.3.2 (upgrading supermarjtinconfiglib from 1.1.6 to 1.1.7
2. Launch the pack and crash trying to load
3. Open latest.log to ignore the uniqueenchantments domino effect and spot your mod's new error causing it to close.

**Crash report (~/logs/latest.log)**
I've extracted specifically your mod's error trace for you, if you need the full file (which you shouldn't, I assure you), let me know.
https://pastebin.com/ZEPyw27m

Downgrading to 1.1.6 fixes the issue, so something must have happened in between.

**Comment by NighthowlerStudios** [comment]
Note seems to be duplicate of #15 however this version of the issue is providing much more detail.

**Comment by SuperMartijn642** [comment]
Welp, seems something changed internally between 1.16 and 1.17 which made it only work for 1.17 and above.
I have fixed it now, thank you for reporting the issue!

**Comment by NighthowlerStudios** [comment]
thought it was a breaking change on the forge side, seems I was right lol.  you're welcome
