### ISSUE TITLE
[Crash] ... Dependency issues

### ISSUE THREAD

**Issue by FAKHORII** [SuperMartijn642/SuperMartijn642sConfigLib#19]
dependency issue on several mods, they ask about version 1.1.0 at least while using the latest version 1.1.8a

**Comment by SuperMartijn642** [comment]
You are likely confusing my core and config libraries.

**Comment by andrey-kun** [comment]
It seems that Fabric doesn't recognize the letter "a" in the version.

```[08:19:35] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'SuperMartijn642's Config Lib' (supermartijn642configlib) 1.1.8a with version 1.1.0 or later.
Unmet dependency listing:
	 - Mod 'Rechiseled' (rechiseled) 1.1.4 requires version 1.1.0 or later of mod 'SuperMartijn642's Config Lib' (supermartijn642configlib), but only the wrong version is present: 1.1.8a!```

**Comment by SuperMartijn642** [comment]
Oh I see, it is indeed supposed to be 1.1.8+a. My build script is supposed to do that, but I guess I might not have set that up correctly for the config library.

**Comment by SuperMartijn642** [comment]
Should be fixed now. Thank you both for reporting the issue!

**Comment by FAKHORII** [comment]
> Should be fixed now. Thank you both for reporting the issue!

THANKS TO YOU for taking care of all this <3
