### ISSUE TITLE
[Bug] ...

### ISSUE THREAD

**Issue by P0Iish** [SuperMartijn642/SuperMartijn642sConfigLib#2]
**Version Info**
- Minecraft, 1.16.5
- Config Lib, 1.0.9-mc1.16

Whenever I start my server the console says Supermartijn642sCoreLib isn't installed. This happens when I try any mod that requires it. FYI I have the Core Lib installed. I tried versions 1.0.6-1.0.9 for MC1.16.

**Screenshots**
![e23d2337-b04c-462c-a9ec-79983e0148af (2)](https://user-images.githubusercontent.com/87307896/125271643-48c5cc80-e30b-11eb-9074-4cfbae7db9b6.png)

**Comment by P0Iish** [comment]
After I wrote this it just magically worked, I still don't know what the problem was though. I haven't changed anything.

**Comment by SuperMartijn642** [comment]
Just a weird coincidence probably. Glad it works now 🙂
