### ISSUE TITLE
[Crash] java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'supermartijn642configlib'!

### ISSUE THREAD

**Issue by ReneMuetti** [SuperMartijn642/SuperMartijn642sConfigLib#23]
**Version Info**
- Minecraft, 1.20.6
- Config Lib, 1.1.8a-fabric-mc1.20.2

**Crash report (~/logs/latest.log)**
[crash-2024-06-02_07.41.16-client.txt](https://github.com/user-attachments/files/15529650/crash-2024-06-02_07.41.16-client.txt)

Please update your MOD version to 1.20.6.
Many thanks :)

**Comment by SuperMartijn642** [comment]
That file is for 1.20.4, not 1.20.6.

**Comment by ReneMuetti** [comment]
That is clear to me. With this ticket I wanted to ask whether the mods will be updated to 1.20.6?

**Comment by SuperMartijn642** [comment]
No idea
