### ISSUE TITLE
[Bug] Failed decoding custom payload supermartijn642configlib:sync_packet

### ISSUE THREAD

**Issue by NielsPilgaard** [SuperMartijn642/SuperMartijn642sConfigLib#25]
**Version Info**
- Minecraft, 1.21.0
- Config Lib, supermartijn642configlib-1.1.8-neoforge-mc1.21

**Description of the Bug**
I cannot connect to a LAN server

**Steps to Reproduce**
- Make a world on one PC, open it to LAN
- Try to join it on another PC
- See error

Logs:
- [latest.log](https://gist.github.com/NielsPilgaard/e9a62ff8a45329ee32270510f1fc574a)
- [disconnect-2024-08-10_11.47.50-client](https://gist.github.com/NielsPilgaard/abac3bb004672dd8a37d78e9fbbec29e)

**Comment by paradust7** [comment]
This is also happening on FTB Unstable 1.21. Identical exception. Versions:
supermartijn642configlib-1.1.8-neoforge-mc1.21.jar
entangled-1.3.18-neoforge-mc1.21.jar

**Comment by SuperMartijn642** [comment]
This was an issue with Entangled (https://github.com/SuperMartijn642/Entangled/issues/89) and should be fixed now in Entangled version 1.3.18a.
Thank you for reporting the issue!
