### ISSUE TITLE
[Crash] Mod crashes upon starting up.

### ISSUE THREAD

**Issue by SlytherTheUndertaker** [SuperMartijn642/SuperMartijn642sConfigLib#26]
**Version Info**
- Minecraft, 1.20.1
- Config Lib, 1.1.8
**Steps to Reproduce**
- Start up game using Modrinth
- Wait for loading to finish

**Crash report (~/logs/latest.log)**
https://pastebin.com/farEhfjB

**Comment by SuperMartijn642** [comment]
The error occurs from Every Compat trying to register a null item. This crash has nothing to do with my config library 🤔
