### ISSUE TITLE
Wrong Version or Missing Update ?

### ISSUE THREAD

**Issue by DarkBreaker09** [SuperMartijn642/SuperMartijn642sConfigLib#5]
Hey there,

I installed Simple Magnets and SuperMartijn642sConfigLib on the latest Version 1.0.9

But when i Start the Game it tells me that SuperMartijn642sConfigLib 1.0.15 or above, and below 1.1.0 is required.

But there is only a 1.0.9 Version.

So how can i Fix that ore is there still an Update coming soon ?

![Inked22c2a4e84ad709147673a057f51c1240](https://user-images.githubusercontent.com/22195721/144966339-c6659b03-dd98-414a-99c0-bf73c20ecc58.jpg)

**Comment by SuperMartijn642** [comment]
That message is for the core lib, not the config lib. I believe Simple Magnets requires both.

https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib
