### ISSUE TITLE
[Bug] config lib 1.1.5  break Additional Enchanted Miner

### ISSUE THREAD

**Issue by moidu21** [SuperMartijn642/SuperMartijn642sConfigLib#7]
**Version Info**
- Minecraft, 1.19
- Config Lib, 1.1.5

**Description of the Bug**
after updating to 1.1.5 some block from Additional Enchanted Miner mod disappear 

**Steps to Reproduce**
run the config lib 1.1.4 and Additional Enchanted Miner mod place a quarry plus and a workbench plus save the world, update to config lib 1.1.5 and run again, block are missing even in  creative tab, downgrade to 1.1.4 solve the issue ( i run it on server)

mod: Additional Enchanted Miner version 19.1
https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner

**Comment by SuperMartijn642** [comment]
That mod does not interact with my config library whatsoever. Please report the issue to them, there is no way this is caused by updating my config library.
