### ISSUE TITLE
The game wont even open [Crash] 

### ISSUE THREAD

**Issue by Dustynzzz** [SuperMartijn642/SuperMartijn642sConfigLib#9]
**Version Info**
- Minecraft, 1.19
- Config Lib, 1.1.6b

**Steps to Reproduce**
...

**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/SuperMartijn642/SuperMartijn642sConfigLib/files/9122041/latest.log)

**Comment by SuperMartijn642** [comment]
`Mod §estoragenetwork§r requires §6forge§r §o41.0.0 or above, and below 41.0.63§r
§7Currently, §6forge§r§7 is §o41.0.98`

Seems like you have mod with modid `storagenetwork` which requires an older Forge version, nothing to do with my config library.
